### PR TITLE
del @cj-wright

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by CJ-Wright** [comment]
I'm still on core, I'll be around, besides you've got this.

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
Azure or anaconda.org seems to be very slow today. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=70627 hangs on "Collecting package metadata (repodata.json): ...working... done" for 30 minutes already...

**Pull request closed without merging**
